### ISSUE TITLE
Unable to login into admin panel in GeniXCMS 1.1.9

### ISSUE THREAD

**Issue by jameswill** [semplon/GeniXCMS#101]
**Describe the bug**
Unable to login into admin panel post installing it successfully. It gives following error.

_**Token not exist, or your time has expired. Please refresh your browser to get a new token.**_

**To Reproduce**
1. Go to admin page
2. add the admin details

**Expected behavior**
Allowed to login

**Comment by semplon** [comment]
@jameswill thank you for the report. i will take check it again. i do can't login either. but i got no token error. i will do check for it. 

once again, thanks

**Comment by semplon** [comment]
fixed

**Comment by jameswill** [comment]
Hello @semplon ,

I am getting the same error in version 1.1.10 i.e : 

_Token not exist, or your time has expired. Please refresh your browser to get a new token._

Also on front-end page the welcome text is not changed i.e Welcome to GenixCMS 1.1.8, which should be 'Welcome to GenixCMS 1.1.10'. 

This text comes from options table under 'value'  column filed corresponding to column 'name' field 'gneex_options'.

So to check further I checked with the code written in insertData() function, which holds the query under $options variable, defined on line 312 in /inc/lib/Install.class.php.

 Please make the change in insert query on line number 382 in /inc/lib/Install.class.php
i.e Welcome to GenixCMS 1.1.8 to Welcome to GenixCMS 1.1.10.

**Comment by semplon** [comment]
hello @jameswill thank you for your reply. i will check it again and see the error. please do check the demo site 

https://demo.genix.me 
username : admin
password : admin

yes i forgot to change the options value at the install class. i will fix it. 

Thank You,

**Comment by jameswill** [comment]
Hello @semplon ,

Thanks for your prompt response. Checked with the demo site as well. Got the same error there as well.

Regards.

**Comment by jameswill** [comment]
Hi,

I am still getting the same error while logging into admin panel in GeniXCMS 1.1.11 version as well.

i.e **_Token not exist, or your time has expired. Please refresh your browser to get a new token._**

However the front end version number issue got resolved.

**Comment by semplon** [comment]
okay, thanks @jameswill for the information. 
I will check it thoroughly. the token validation is too strict I suppose. 

Did You install it at localhost or on the internet ? I need more information to do the modification. 

please run this at the php and share the output

```php
<?php
foreach($_SERVER as $k => $v) {
    echo $k . ": " . $v . "<br>";
}
```

**Comment by jameswill** [comment]
Hi,

Sorry for the late reply.

I have installed on 

Attaching the output your were asking for.

HTTP_HOST: DOMAIN.COM
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5
HTTP_ACCEPT_ENCODING: gzip, deflate
HTTP_CONNECTION: keep-alive
HTTP_REFERER: http://DOMAIN.COM/DIRECTORY/
HTTP_COOKIE: SOFTCookies6415_sid=M8vpEWvJBX6bS8YBPvoKZTNpRba9mZTq
HTTP_UPGRADE_INSECURE_REQUESTS: 1
PATH: /sbin:/usr/sbin:/bin:/usr/bin
SERVER_SIGNATURE:
SERVER_SOFTWARE: Apache
SERVER_NAME: DOMAIN.COM
SERVER_ADDR: LINUX_IP
SERVER_PORT: 80
REMOTE_ADDR: REMOTE_IP
DOCUMENT_ROOT: /home/USER/public_html
SERVER_ADMIN: admin@admin.com
SCRIPT_FILENAME: /home/USER/public_html/DIRECTORY/test.php
REMOTE_PORT: 54321
GATEWAY_INTERFACE: CGI/1.1
SERVER_PROTOCOL: HTTP/1.1
REQUEST_METHOD: GET
QUERY_STRING:
REQUEST_URI: /DIRECTORY/test.php
SCRIPT_NAME: /DIRECTORY/test.php
PHP_SELF: /DIRECTORY/test.php
REQUEST_TIME_FLOAT: 1601526719.4204
REQUEST_TIME: 1601526719
argv: Array
argc: 0

Since this is a public platform, I have renamed the private information with the general term in CAPITALS.

**Comment by semplon** [comment]
Hello @jameswill thanks for your reply. I know now why does it's now work. Your server didn't passing the $_SERVER['HTTP_SCHEME'] 

New update of GeniXCMS need this variable to validate token. When the value is not match it won't work.

**Comment by jameswill** [comment]
Hi,

What would be the work around for this ? Or what could be solution for this ?

**Comment by semplon** [comment]
I think just removing $protocol at the Token validate method will fix this problem. 

I will update it soon, i am still busy with another project.

**Comment by jameswill** [comment]
Hi,

Sure. I shall wait for the new version with the fix.

Please let me know.

**Comment by jameswill** [comment]
Hi,

I wanted to know why is this issue closed ?

Is this resolved ? I was notified that with the new release this issue will resolve ? Is there new update available with the fix ?

**Comment by semplon** [comment]
Hi, @jameswill yes, it does. It's been fixed.

**Comment by jameswill** [comment]
Hello @semplon,

The issue still persists in 1.1.11 version. I have tested the manual installation on Centos 6.9 Final with PHP 7.2.24, MYSQL 5.5.62, Apache 2.2.34. Still getting the same error i.e:

**Token not exist, or your time has expired. Please refresh your browser to get a new token.**

Could you please replicate this issue and post a fix for the same?.
